# Generated by Django 6.0.2 on 2026-03-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Plate', models.IntegerField()),
                ('Car_Model', models.CharField(max_length=100)),
                ('Car_Type', models.CharField(max_length=20)),
                ('Mileage', models.IntegerField()),
                ('Engine_Type', models.CharField(max_length=15)),
                ('Make_Date', models.DateField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
